name: martin gagne
favicon: null
layout_spectrum: 0.9231098357122391
typography_spectrum: 0.5749462509993464
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.42191224661655724
  lightness: 0.18073437572456896
  saturation: 0.15886378893628716
  rhythmicContrast: 0.04907503561116755
purpose: []
