name: martin gagne
favicon: null
layout_spectrum: 0.24786
typography_spectrum: 0.5749462509993464
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080204'
    - '#bac1c1'
    - '#293841'
    - '#4c6992'
    - '#ffa54b'
  brandStrength: 0
  lightness: 0.18073437572456896
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
